# Generated by Django 3.2.3 on 2022-03-11 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charity',
        ),
    ]
