# Generated by Django 3.2.3 on 2022-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
