# Generated by Django 3.2.3 on 2022-03-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_alter_charity_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charity',
        ),
    ]
