# Generated by Django 3.2.3 on 2022-03-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0006_charity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charity',
        ),
    ]
