# Generated by Django 3.2.3 on 2022-03-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('explore', '0007_delete_charity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('charity_theme', models.CharField(max_length=250)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('pic_link', models.CharField(max_length=1000)),
                ('charity_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='')),
                ('username', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
            ],
        ),
    ]
