# Generated by Django 4.0.2 on 2022-03-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0008_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='certificate',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
