# Generated by Django 2.2.24 on 2022-04-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0009_alter_charity_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='charity',
            name='password',
            field=models.CharField(default=123456, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
