# Generated by Django 2.2.24 on 2022-04-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0010_auto_20220404_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='charity_id',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='charity',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
