# Generated by Django 3.2.3 on 2022-04-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0011_auto_20220404_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
