# Generated by Django 3.2.3 on 2022-04-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0012_charity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='identifier',
            field=models.CharField(max_length=40),
        ),
    ]
